version: 2.1

orbs:
  qodana: jetbrains/qodana@2023.1
  docker: circleci/docker@2.1.2
  slack: circleci/slack@4.3.0

commands:
  trigger_slack_notification:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
          
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan

  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: |
          mvn test

  build-docker:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - trigger_slack_notification
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: |
          DOCKERHUB_REPO=datnguyen293
          DOCKER_IMAGE=bon-voyage

          docker build -t $DOCKERHUB_REPO/$DOCKER_IMAGE:latest .
      - notify_slack_error
      - notify_slack_pass

workflows:
  build-service:
    jobs:
      - code-quality:
          context: bon-voyage-context
      - test
      - build-docker:
          context: slack-notification
          requires:
            - code-quality
            - test
